import type { Requirement } from '../../types/index.js';

export const Q1_REQUIREMENTS: Requirement[] = [
  {
    id: 'Q1-R1',
    section: 'Question 1 - Facebook/Meta',
    title: 'Business & Marketing Foundation',
    description: 'Define selected business, target market, 4Ps, 4As, business feasibility summary',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q1-R2',
    section: 'Question 1 - Facebook/Meta',
    title: 'Facebook Business Page Setup',
    description: 'Create/redesign Facebook Business Page with profile/cover, About section, category, username, CTA button, Featured section, Page settings',
    priority: 'high',
    automatable: false,
    tasks: [],
  },
  {
    id: 'Q1-R3',
    section: 'Question 1 - Facebook/Meta',
    title: 'Advanced Page Setup',
    description: 'Professional Dashboard settings, Page access/roles, linked accounts, preferences, audience/controls, moderation setup, event/collaboration features',
    priority: 'high',
    automatable: false,
    tasks: [],
  },
  {
    id: 'Q1-R4',
    section: 'Question 1 - Facebook/Meta',
    title: 'Meta Business Suite',
    description: 'Social media management via Meta Suite: Inbox/message automation, planner/content scheduling, AI-assisted weekly content plan',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q1-R5',
    section: 'Question 1 - Facebook/Meta',
    title: 'Facebook Ads Campaign',
    description: 'Complete campaign with objective, structure, budget strategy, audience, placements, at least two ad sets/audience variations',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q1-R6',
    section: 'Question 1 - Facebook/Meta',
    title: 'Lead Generation',
    description: 'Lead Ad or Carousel Ad with Instant Form: form fields, offer, CTA, follow-up message',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q1-R7',
    section: 'Question 1 - Facebook/Meta',
    title: 'A/B Testing',
    description: 'One meaningful A/B test: creative, headline, audience or CTA variation',
    priority: 'medium',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q1-R8',
    section: 'Question 1 - Facebook/Meta',
    title: 'Evidence Collection',
    description: 'Screenshots of Page optimization, Meta Suite, campaign/ad set/ad setup, audience, form, planner',
    priority: 'high',
    automatable: false,
    tasks: [],
  },
];

export const Q2_REQUIREMENTS: Requirement[] = [
  {
    id: 'Q2-R1',
    section: 'Question 2 - LinkedIn',
    title: 'LinkedIn Profile Optimization',
    description: 'Optimize professional profile: headline, About section, skills, experience/service positioning, profile/cover recommendations',
    priority: 'high',
    automatable: false,
    tasks: [],
  },
  {
    id: 'Q2-R2',
    section: 'Question 2 - LinkedIn',
    title: 'LinkedIn Company Page',
    description: 'Create company/agency page with professional branding, description, services, CTA',
    priority: 'high',
    automatable: false,
    tasks: [],
  },
  {
    id: 'Q2-R3',
    section: 'Question 2 - LinkedIn',
    title: 'LinkedIn Lead Generation Campaign',
    description: 'Design LinkedIn Ads campaign: objective, target audience, budget, ad creative/copy, Lead Gen Form',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q2-R4',
    section: 'Question 2 - LinkedIn',
    title: 'Audience Strategy',
    description: 'Define at least two audience segments using location, industry, job title, company size, seniority, interests',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q2-R5',
    section: 'Question 2 - LinkedIn',
    title: 'AI-Assisted Planning',
    description: 'Use AI tool to prepare client persona, campaign angle, 7-day content/outreach plan or lead-gen workflow. Include prompt and improved final output',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q2-R6',
    section: 'Question 2 - LinkedIn',
    title: 'Client Hunting',
    description: 'Identify method to find potential clients via LinkedIn, Facebook/Meta communities, directories, professional networks. List 10+ prospects',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q2-R7',
    section: 'Question 2 - LinkedIn',
    title: 'Outreach Messages',
    description: 'Write connection message, professional first outreach message, and follow-up message',
    priority: 'high',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q2-R8',
    section: 'Question 2 - LinkedIn',
    title: 'Performance & Improvement',
    description: 'Metrics for LinkedIn campaign and outreach, improvement strategy',
    priority: 'medium',
    automatable: true,
    tasks: [],
  },
  {
    id: 'Q2-R9',
    section: 'Question 2 - LinkedIn',
    title: 'Evidence Collection',
    description: 'Screenshots of LinkedIn profile/page setup, audience/campaign concept, Lead Gen Form, AI prompt/output, prospect research',
    priority: 'high',
    automatable: false,
    tasks: [],
  },
];

export const ALL_REQUIREMENTS = [...Q1_REQUIREMENTS, ...Q2_REQUIREMENTS];
